/**
 * MutationIconStrip — a horizontal HUD strip of acquired mutation icons.
 *
 * Each call to `addMutation` appends a glowing 32x32 icon to the right of the
 * previous one with a juicy pop-in tween. Hovering an icon reveals a tiny
 * tooltip with the mutation's name. The component is defensive: every public
 * entry point is wrapped so a missing texture or a tween-engine hiccup can
 * never throw and break the rest of the HUD.
 */

import Phaser from 'phaser'
import { COLORS, DEPTHS } from '@/config/constants'
import type { Mutation } from '@/types'

/** Visual layout constants for the strip. */
const ICON_SIZE = 32
const ICON_GAP = 8
const ICON_STEP = ICON_SIZE + ICON_GAP
const GLOW_COLOR = COLORS.BIOMASS
const TOOLTIP_OFFSET_Y = ICON_SIZE * 0.5 + 10

export class MutationIconStrip extends Phaser.GameObjects.Container {
  /** Running horizontal offset for the next icon's centre. */
  private nextX = ICON_SIZE * 0.5

  /** Single shared tooltip reused across all icons (created lazily). */
  private tooltip: Phaser.GameObjects.Text | null = null
  private tooltipBg: Phaser.GameObjects.Rectangle | null = null

  constructor(scene: Phaser.Scene, x: number, y: number) {
    super(scene, x, y)

    this.setDepth(DEPTHS.VIGNETTE)
    this.setScrollFactor(0)

    // Register with the scene so it participates in the display/update list.
    scene.add.existing(this)
  }

  /**
   * Append a mutation icon to the strip. Never throws: if the texture is
   * missing or any Phaser call fails, the call is silently skipped.
   */
  addMutation(mutation: Mutation): void {
    try {
      if (!mutation || !mutation.iconKey) {
        return
      }

      const cx = this.nextX

      // Soft glow halo behind the icon (additive for a luminous look).
      const glow = this.scene.add.image(cx, 0, this.resolveTexture('soft_glow'))
      glow.setDisplaySize(ICON_SIZE * 1.7, ICON_SIZE * 1.7)
      glow.setTint(GLOW_COLOR)
      glow.setAlpha(0.0)
      glow.setBlendMode(Phaser.BlendModes.ADD)
      glow.setScrollFactor(0)
      this.add(glow)

      // The crisp icon itself.
      const icon = this.scene.add.image(cx, 0, this.resolveTexture(mutation.iconKey))
      icon.setDisplaySize(ICON_SIZE, ICON_SIZE)
      icon.setScrollFactor(0)
      icon.setScale(0)
      this.add(icon)

      this.advance()
      this.attachHover(icon, glow, mutation.name)
      this.playPopIn(icon, glow)
    } catch {
      // Swallow — the HUD must keep working even if one icon fails.
    }
  }

  /** Resolve a texture key, falling back to a known-safe glow if absent. */
  private resolveTexture(key: string): string {
    if (this.scene.textures && this.scene.textures.exists(key)) {
      return key
    }
    // SOFT_GLOW is always generated by the TextureFactory at boot, so it is a
    // safe visual fallback that keeps `add.image` from erroring on a missing key.
    return 'soft_glow'
  }

  /** Advance the internal cursor for the next icon. */
  private advance(): void {
    this.nextX += ICON_STEP
  }

  /** Pop-in tween: scale 0 → 1.15 → 1.0 with the glow fading up then settling. */
  private playPopIn(icon: Phaser.GameObjects.Image, glow: Phaser.GameObjects.Image): void {
    try {
      this.scene.tweens.add({
        targets: icon,
        scale: { from: 0, to: 1.15 },
        duration: 180,
        ease: 'Back.easeOut',
        onComplete: () => {
          if (!icon.active) {
            return
          }
          this.scene.tweens.add({
            targets: icon,
            scale: 1.0,
            duration: 120,
            ease: 'Sine.easeInOut',
          })
        },
      })

      // Glow flashes brightly on arrival, then relaxes to a gentle idle pulse.
      this.scene.tweens.add({
        targets: glow,
        alpha: { from: 0.0, to: 0.55 },
        duration: 180,
        ease: 'Quad.easeOut',
        yoyo: true,
        hold: 60,
        onComplete: () => {
          if (!glow.active) {
            return
          }
          glow.setAlpha(0.18)
          this.scene.tweens.add({
            targets: glow,
            alpha: 0.3,
            duration: 1100,
            ease: 'Sine.easeInOut',
            yoyo: true,
            repeat: -1,
          })
        },
      })
    } catch {
      // If the tween engine is unavailable, just snap to the final state.
      icon.setScale(1.0)
      glow.setAlpha(0.22)
    }
  }

  /** Wire pointer hover on an icon to show/hide the shared name tooltip. */
  private attachHover(
    icon: Phaser.GameObjects.Image,
    glow: Phaser.GameObjects.Image,
    name: string,
  ): void {
    try {
      icon.setInteractive({ useHandCursor: true })

      icon.on('pointerover', () => {
        this.showTooltip(icon.x, name)
        if (glow.active) {
          glow.setAlpha(0.5)
        }
      })

      icon.on('pointerout', () => {
        this.hideTooltip()
        if (glow.active) {
          glow.setAlpha(0.22)
        }
      })

      // Ensure listeners are cleaned up if the icon is ever destroyed.
      icon.once('destroy', () => {
        icon.removeAllListeners()
      })
    } catch {
      // Hover is purely cosmetic; ignore failures.
    }
  }

  /** Show the tooltip text centred above the given local x. */
  private showTooltip(localX: number, name: string): void {
    try {
      const text = name && name.length > 0 ? name : '???'

      if (!this.tooltip) {
        this.tooltipBg = this.scene.add.rectangle(0, 0, 10, 10, COLORS.UI_PANEL, 0.85)
        this.tooltipBg.setScrollFactor(0)
        this.tooltipBg.setStrokeStyle(1, COLORS.UI_PANEL_BORDER, 0.9)
        this.add(this.tooltipBg)

        this.tooltip = this.scene.add.text(0, 0, '', {
          fontFamily: 'monospace',
          fontSize: '12px',
          color: '#f2fbff',
        })
        this.tooltip.setScrollFactor(0)
        this.tooltip.setOrigin(0.5, 0.5)
        this.add(this.tooltip)
      }

      this.tooltip.setText(text)
      this.tooltip.setPosition(localX, -TOOLTIP_OFFSET_Y)
      this.tooltip.setVisible(true)

      if (this.tooltipBg) {
        this.tooltipBg.setSize(this.tooltip.width + 12, this.tooltip.height + 8)
        this.tooltipBg.setPosition(localX, -TOOLTIP_OFFSET_Y)
        this.tooltipBg.setVisible(true)
      }
    } catch {
      // Tooltip is optional polish; ignore failures.
    }
  }

  /** Hide the shared tooltip if it exists. */
  private hideTooltip(): void {
    try {
      if (this.tooltip) {
        this.tooltip.setVisible(false)
      }
      if (this.tooltipBg) {
        this.tooltipBg.setVisible(false)
      }
    } catch {
      // No-op.
    }
  }
}
